In [1]:
Limit = 2000
soroMove_per_urMove = 5

## open port

In [23]:
!echo 'qwer1234'| sudo -S chmod a+rw /dev/ttyUSB1

[sudo] password for terry-q: 

## BASIC USAGE OF XL320 CLASS

In [24]:
import os, time
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import sys
sys.path.append(".")
from model.class_xc330 import xc330

# from class_grp import grp
%matplotlib inline
print ("PACKAGES LOADED.")


PACKAGES LOADED.


## INSTANTIATE XL320 

In [25]:
snapbot = xc330('SNAPBOT', _USB_NUM=1)

[SNAPBOT] INSTANTIATED AT [/dev/ttyUSB1]


## CONNECT

In [26]:
snapbot.connect()

# snapbot.IDX_LIST = [21, 22, 15, 16, 13, 14, 17, 18]

[SNAPBOT] CONNECT
 SUCCEEDED TO OPEN THE PORT!
 SUCCEEDED TO CHANGE THE BAUDRATE!
COMMUNICATION SUCCESS
[SNAPBOT] DETECT ID
[SNAPBOT] [4]MOTORS DETECTED 
[SNAPBOT] ID_LIST:[[13, 14, 15, 16]]


In [27]:
snapbot.set_torque([1])
print ("TORQUE ON")


TORQUE ON


In [28]:
snapbot.set_operatingmode([4])


## Calibrate (Preset Pose)

In [29]:
snapbot.set_torque([0])
time.sleep(2)
snapbot.set_torque([1])

currpos = snapbot.get_currpos()
minmaxInterval = 5000
snapbot.set_minmaxpos(currpos-np.ones_like(currpos)*minmaxInterval,currpos+np.ones_like(currpos)*minmaxInterval)

initpos = [1695, 1443, 2725, 1502] #  np.array([15,-15,30,-15]
snapbot.set_goalposcluster(initpos,1)


In [30]:
print ("INITIALIZE POSITION")
currpos = snapbot.get_currpos()
print (currpos)

minmaxInterval = 5000
snapbot.set_minmaxpos(currpos-np.ones_like(currpos)*minmaxInterval,currpos+np.ones_like(currpos)*minmaxInterval)

INITIALIZE POSITION
[1688 1448 2712 1509]


In [34]:
##Grasp
l1=0
l2=0
l3=0
l4=0

pos = currpos+np.array([l1,l2,l3,l4])
pos = pos.astype(np.int)
snapbot.set_goalposcluster(pos,1)

In [74]:
np.random.rand(4) * np.array([1,-1,1,-1])

array([ 0.12203823, -0.49517691,  0.03438852, -0.9093204 ])

In [76]:
import json
# np.random.seed(42)
# Data to be written
dictionary ={}

urposjson = {0:[2.0,1.2,0.2]}
urfileidx = 0


for soroMove_Idx in range(soroMove_per_urMove):
    delta = (np.random.rand(4)) * np.array([1,-1,1,-1]) * Limit
    delta = delta.astype(np.int)
    print(delta)
    pos = currpos + delta
    snapbot.set_goalposcluster(pos,1)
    
    dictionary[soroMove_Idx] = {"RPY":list(urposjson[urfileidx]),"motor_control":list(delta)}
    time.sleep(3)
    
# Serializing json 
json_object = json.dumps(dictionary)

name = "results/URIdx_{}_.json".format(urfileidx)

# Writing to sample.json
with open(name, "w") as outfile:
    outfile.write(json_object)
    

[  561 -1085   281 -1604]
[  149 -1973  1544  -397]
[   11 -1630  1413 -1458]
[1542 -148  716 -231]
[ 1726 -1246   661  -127]
