In [1]:
import json
from pathlib import Path
import copy

from numpy import single

filepath = Path('1002/repeat_test')

file_storage = {'first':[], 'second':[], 'third':[],'fourth':[], 'zero':[]}
for singlefile in filepath.iterdir():
    with open(str(singlefile), "r") as st_json:
        st_python = json.load(st_json)
    
    temp = copy.deepcopy(st_python)
    
    for key in file_storage.keys():
        if key in str(singlefile):
            file_storage[key].append(temp)
            break


In [8]:
## Unlabeled markers ##
import numpy as np
unlabeled_markers_list = []

for markers in file_storage['first']:
    if len(markers['unlabeled_markers_list']) != 1:
        print("Ghost markers Found! ", markers)
        continue 
    unlabeled_markers_list.append([
        markers['unlabeled_markers_list'][0]['x'], 
        markers['unlabeled_markers_list'][0]['y'], 
        markers['unlabeled_markers_list'][0]['z']
        ])
    
unlabeled_markers_array = np.array(unlabeled_markers_list) * 1000
unlabeled_markers_array = unlabeled_markers_array[:5]
print(unlabeled_markers_array)
print("standard deviation along axis:", np.std(unlabeled_markers_array,axis=0))

[[-315.01680613  950.83194971  512.79842854]
 [-299.70884323  950.20407438  516.87222719]
 [-299.74704981  950.14077425  516.52771235]
 [-316.57227874  950.91164112  510.18881798]
 [-311.29395962  950.9626627   512.31187582]]
standard deviation along axis: [7.3393466  0.36043534 2.57368127]


In [49]:
markers['platform_markers_list']

[{'x': -0.31161385774612427, 'y': 0.8361464142799377, 'z': 0.4496890604496002},
 {'x': -0.263024240732193, 'y': 0.8363696932792664, 'z': 0.49373042583465576},
 {'x': -0.31413090229034424, 'y': 0.8359094858169556, 'z': 0.5498851537704468},
 {'x': -0.3622158467769623, 'y': 0.8346413373947144, 'z': 0.49857214093208313}]

In [72]:
## Platform markers ##

import numpy as np
platform_markers_list = []

for markers in file_storage['first']:
    assert len(markers['platform_markers_list']) == 4
    platform_markers_list.append([
        markers['platform_markers_list'][0]['x'], 
        markers['platform_markers_list'][0]['y'], 
        markers['platform_markers_list'][0]['z']
        ])
    
platform_markers_array = np.array(platform_markers_list) * 1000
print(platform_markers_array)
print("standard deviation along axis:", np.std(platform_markers_array,axis=0))

TypeError: list indices must be integers or slices, not str

## Mocap Noise

In [73]:
import json
from pathlib import Path
import copy

from numpy import single

filepath = Path('mocap/data')

file_storage = []
for singlefile in filepath.iterdir():
    with open(str(singlefile), "r") as st_json:
        st_python = json.load(st_json)
    
    temp = copy.deepcopy(st_python)
    file_storage.append(temp)
    

In [74]:
## Unlabeled markers ##
import numpy as np
unlabeled_markers_list = []

for markers in file_storage:
    if len(markers['unlabeled_markers_list']) != 1:
        print("Ghost markers Found! ", markers)
        continue 
    unlabeled_markers_list.append([
        markers['unlabeled_markers_list'][0]['x'], 
        markers['unlabeled_markers_list'][0]['y'], 
        markers['unlabeled_markers_list'][0]['z']
        ])
    
unlabeled_markers_array = np.array(unlabeled_markers_list) * 1000
print(unlabeled_markers_array)
print("standard deviation along axis:", np.std(unlabeled_markers_array,axis=0))

[[-304.12590504  966.06892347  502.5408268 ]
 [-304.13126945  966.07208252  502.52890587]
 [-304.17954922  966.07422829  502.55250931]
 ...
 [-304.14026976  966.07607603  502.53981352]
 [-304.07938361  966.06093645  502.55072117]
 [-304.21870947  966.06713533  502.56246328]]
standard deviation along axis: [0.05029348 0.00664256 0.01335146]
